import type { Exercise } from '../types'

export const seedExercises: Exercise[] = [
  // ========== CHEST (4) ==========
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Barbell Bench Press',
    category: 'chest',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/rT7DgCr-3pg',
    thumbnailUrl: 'https://img.youtube.com/vi/rT7DgCr-3pg/mqdefault.jpg',
    instructions: [
      'Lie flat on the bench with feet firmly on the floor and eyes under the bar.',
      'Grip the bar slightly wider than shoulder width with wrists straight.',
      'Unrack the bar and lower it to your mid-chest with elbows at roughly 45 degrees.',
      'Press the bar back up to full lockout, keeping your shoulder blades retracted.',
    ],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front deltoids', 'triceps'],
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Dumbbell Incline Press',
    category: 'chest',
    equipment: 'dumbbell',
    videoUrl: 'https://www.youtube.com/embed/8iPEnn-ltC8',
    thumbnailUrl: 'https://img.youtube.com/vi/8iPEnn-ltC8/mqdefault.jpg',
    instructions: [
      'Set the bench to a 30-45 degree incline and sit back with a dumbbell in each hand.',
      'Press the dumbbells up from shoulder level until your arms are fully extended.',
      'Lower the dumbbells slowly to chest level, keeping elbows at about 45 degrees.',
      'Squeeze your chest at the top of the movement and repeat.',
    ],
    primaryMuscles: ['upper chest'],
    secondaryMuscles: ['front deltoids', 'triceps'],
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    name: 'Cable Chest Fly',
    category: 'chest',
    equipment: 'cable',
    videoUrl: 'https://www.youtube.com/embed/Iwe6AmxVf7o',
    thumbnailUrl: 'https://img.youtube.com/vi/Iwe6AmxVf7o/mqdefault.jpg',
    instructions: [
      'Set both pulleys to shoulder height and grab a handle in each hand.',
      'Step forward into a staggered stance with a slight lean forward.',
      'With a slight bend in the elbows, bring your hands together in a hugging arc.',
      'Slowly return to the starting position, feeling the stretch in your chest.',
    ],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front deltoids'],
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    name: 'Machine Chest Press',
    category: 'chest',
    equipment: 'machine',
    videoUrl: 'https://www.youtube.com/embed/xUm0BiZCWlQ',
    thumbnailUrl: 'https://img.youtube.com/vi/xUm0BiZCWlQ/mqdefault.jpg',
    instructions: [
      'Adjust the seat so the handles are at mid-chest height.',
      'Sit back firmly with feet flat on the floor and grip the handles.',
      'Press the handles forward until your arms are fully extended without locking elbows.',
      'Slowly return to the starting position under control.',
    ],
    primaryMuscles: ['chest'],
    secondaryMuscles: ['front deltoids', 'triceps'],
  },

  // ========== BACK (4) ==========
  {
    id: '00000000-0000-0000-0000-000000000005',
    name: 'Barbell Bent-Over Row',
    category: 'back',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/FWJR5Ve8bnQ',
    thumbnailUrl: 'https://img.youtube.com/vi/FWJR5Ve8bnQ/mqdefault.jpg',
    instructions: [
      'Stand with feet shoulder-width apart, hinge at the hips to about 45 degrees.',
      'Grip the bar slightly wider than shoulder width with an overhand grip.',
      'Pull the bar to your lower chest, squeezing your shoulder blades together.',
      'Lower the bar under control back to the starting position.',
    ],
    primaryMuscles: ['lats', 'upper back'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'lower back'],
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    name: 'Dumbbell Single-Arm Row',
    category: 'back',
    equipment: 'dumbbell',
    videoUrl: 'https://www.youtube.com/embed/pYcpY20QaE8',
    thumbnailUrl: 'https://img.youtube.com/vi/pYcpY20QaE8/mqdefault.jpg',
    instructions: [
      'Place one knee and hand on a bench with the other foot on the floor.',
      'Hold a dumbbell in the free hand with arm fully extended.',
      'Pull the dumbbell up toward your hip, driving the elbow back.',
      'Lower the dumbbell under control and repeat for all reps before switching sides.',
    ],
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'rhomboids'],
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    name: 'Cable Lat Pulldown',
    category: 'back',
    equipment: 'cable',
    videoUrl: 'https://www.youtube.com/embed/CAwf7n6Luuc',
    thumbnailUrl: 'https://img.youtube.com/vi/CAwf7n6Luuc/mqdefault.jpg',
    instructions: [
      'Sit at the lat pulldown machine with thighs secured under the pads.',
      'Grip the bar wider than shoulder width with an overhand grip.',
      'Pull the bar down to your upper chest, leading with your elbows.',
      'Slowly return the bar to the top, maintaining tension in your lats.',
    ],
    primaryMuscles: ['lats'],
    secondaryMuscles: ['biceps', 'rear deltoids', 'rhomboids'],
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    name: 'Machine Seated Row',
    category: 'back',
    equipment: 'machine',
    videoUrl: 'https://www.youtube.com/embed/GZbfZ033f74',
    thumbnailUrl: 'https://img.youtube.com/vi/GZbfZ033f74/mqdefault.jpg',
    instructions: [
      'Adjust the chest pad and seat height so you can reach the handles comfortably.',
      'Sit with your chest against the pad, grip the handles.',
      'Pull the handles toward your torso, squeezing your shoulder blades together.',
      'Slowly release back to the starting position without letting the weight stack slam.',
    ],
    primaryMuscles: ['lats', 'rhomboids'],
    secondaryMuscles: ['biceps', 'rear deltoids'],
  },

  // ========== SHOULDERS (4) ==========
  {
    id: '00000000-0000-0000-0000-000000000009',
    name: 'Barbell Overhead Press',
    category: 'shoulders',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/2yjwXTZQDDI',
    thumbnailUrl: 'https://img.youtube.com/vi/2yjwXTZQDDI/mqdefault.jpg',
    instructions: [
      'Stand with feet shoulder-width apart and unrack the bar at collarbone height.',
      'Brace your core and press the bar straight overhead.',
      'Lock out the bar directly over the midfoot with biceps near your ears.',
      'Lower the bar back to the starting position under control.',
    ],
    primaryMuscles: ['front deltoids', 'lateral deltoids'],
    secondaryMuscles: ['triceps', 'upper chest', 'traps'],
  },
  {
    id: '00000000-0000-0000-0000-000000000010',
    name: 'Dumbbell Lateral Raise',
    category: 'shoulders',
    equipment: 'dumbbell',
    videoUrl: 'https://www.youtube.com/embed/3VcKaXpzqRo',
    thumbnailUrl: 'https://img.youtube.com/vi/3VcKaXpzqRo/mqdefault.jpg',
    instructions: [
      'Stand upright holding a dumbbell in each hand at your sides.',
      'With a slight bend in the elbows, raise your arms out to the sides.',
      'Lift until your arms are parallel to the floor, leading with your elbows.',
      'Lower the dumbbells slowly back to your sides.',
    ],
    primaryMuscles: ['lateral deltoids'],
    secondaryMuscles: ['traps', 'front deltoids'],
  },
  {
    id: '00000000-0000-0000-0000-000000000011',
    name: 'Cable Face Pull',
    category: 'shoulders',
    equipment: 'cable',
    videoUrl: 'https://www.youtube.com/embed/rep-qVOkqgk',
    thumbnailUrl: 'https://img.youtube.com/vi/rep-qVOkqgk/mqdefault.jpg',
    instructions: [
      'Set the cable pulley to upper chest height and attach a rope handle.',
      'Grip the rope with an overhand grip and step back to create tension.',
      'Pull the rope toward your face, flaring your elbows high and wide.',
      'Squeeze your rear deltoids and upper back, then return under control.',
    ],
    primaryMuscles: ['rear deltoids'],
    secondaryMuscles: ['traps', 'rhomboids', 'rotator cuff'],
  },
  {
    id: '00000000-0000-0000-0000-000000000012',
    name: 'Machine Shoulder Press',
    category: 'shoulders',
    equipment: 'machine',
    videoUrl: 'https://www.youtube.com/embed/Wqq43dKoG2Q',
    thumbnailUrl: 'https://img.youtube.com/vi/Wqq43dKoG2Q/mqdefault.jpg',
    instructions: [
      'Adjust the seat so the handles start at shoulder height.',
      'Sit with your back flat against the pad and grip the handles.',
      'Press the handles overhead until your arms are fully extended.',
      'Lower the weight back to shoulder height under control.',
    ],
    primaryMuscles: ['front deltoids', 'lateral deltoids'],
    secondaryMuscles: ['triceps', 'traps'],
  },

  // ========== ARMS (4) ==========
  {
    id: '00000000-0000-0000-0000-000000000013',
    name: 'Barbell Curl',
    category: 'arms',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/kwG2ipFRgFo',
    thumbnailUrl: 'https://img.youtube.com/vi/kwG2ipFRgFo/mqdefault.jpg',
    instructions: [
      'Stand with feet shoulder-width apart, gripping the barbell with an underhand grip.',
      'Keep your elbows pinned to your sides throughout the movement.',
      'Curl the bar up toward your shoulders by contracting your biceps.',
      'Lower the bar slowly back to the starting position without swinging.',
    ],
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms', 'brachialis'],
  },
  {
    id: '00000000-0000-0000-0000-000000000014',
    name: 'Dumbbell Hammer Curl',
    category: 'arms',
    equipment: 'dumbbell',
    videoUrl: 'https://www.youtube.com/embed/zC3nLlEvin4',
    thumbnailUrl: 'https://img.youtube.com/vi/zC3nLlEvin4/mqdefault.jpg',
    instructions: [
      'Stand upright with a dumbbell in each hand, palms facing your torso.',
      'Keep your elbows stationary and curl the dumbbells up.',
      'Squeeze at the top, maintaining the neutral wrist position throughout.',
      'Lower the dumbbells under control back to the starting position.',
    ],
    primaryMuscles: ['brachialis', 'biceps'],
    secondaryMuscles: ['forearms'],
  },
  {
    id: '00000000-0000-0000-0000-000000000015',
    name: 'Cable Tricep Pushdown',
    category: 'arms',
    equipment: 'cable',
    videoUrl: 'https://www.youtube.com/embed/2-LAMcpzODU',
    thumbnailUrl: 'https://img.youtube.com/vi/2-LAMcpzODU/mqdefault.jpg',
    instructions: [
      'Attach a straight bar or rope to the high pulley of a cable machine.',
      'Stand facing the machine, grip the attachment with elbows at your sides.',
      'Push the handle down until your arms are fully extended.',
      'Slowly return to the starting position, keeping elbows pinned.',
    ],
    primaryMuscles: ['triceps'],
    secondaryMuscles: ['forearms'],
  },
  {
    id: '00000000-0000-0000-0000-000000000016',
    name: 'Band Bicep Curl',
    category: 'arms',
    equipment: 'band',
    videoUrl: 'https://www.youtube.com/embed/PqyMIssaDBQ',
    thumbnailUrl: 'https://img.youtube.com/vi/PqyMIssaDBQ/mqdefault.jpg',
    instructions: [
      'Stand on the center of a resistance band with feet shoulder-width apart.',
      'Grip both ends of the band with an underhand grip.',
      'Curl your hands up toward your shoulders, keeping elbows at your sides.',
      'Lower back down slowly, maintaining tension on the band throughout.',
    ],
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms', 'brachialis'],
  },

  // ========== LEGS (5) ==========
  {
    id: '00000000-0000-0000-0000-000000000017',
    name: 'Barbell Back Squat',
    category: 'legs',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/ultWZbUMPL8',
    thumbnailUrl: 'https://img.youtube.com/vi/ultWZbUMPL8/mqdefault.jpg',
    instructions: [
      'Position the bar on your upper traps, unrack and step back with feet shoulder-width apart.',
      'Brace your core and initiate the squat by pushing your hips back and bending your knees.',
      'Descend until your thighs are at least parallel to the floor.',
      'Drive through your feet to stand back up to the starting position.',
    ],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'lower back', 'core'],
  },
  {
    id: '00000000-0000-0000-0000-000000000018',
    name: 'Dumbbell Lunges',
    category: 'legs',
    equipment: 'dumbbell',
    videoUrl: 'https://www.youtube.com/embed/D7KaRcUTQeE',
    thumbnailUrl: 'https://img.youtube.com/vi/D7KaRcUTQeE/mqdefault.jpg',
    instructions: [
      'Stand upright holding a dumbbell in each hand at your sides.',
      'Step forward with one leg and lower your hips until both knees are at 90 degrees.',
      'Keep your torso upright and front knee tracking over your toes.',
      'Push through your front foot to return to the starting position and alternate legs.',
    ],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves', 'core'],
  },
  {
    id: '00000000-0000-0000-0000-000000000019',
    name: 'Machine Leg Press',
    category: 'legs',
    equipment: 'machine',
    videoUrl: 'https://www.youtube.com/embed/IZxyjW7MPJQ',
    thumbnailUrl: 'https://img.youtube.com/vi/IZxyjW7MPJQ/mqdefault.jpg',
    instructions: [
      'Sit in the leg press machine with your back flat against the pad.',
      'Place your feet shoulder-width apart on the platform.',
      'Release the safety handles and lower the platform until knees are at 90 degrees.',
      'Press the platform back up without fully locking your knees.',
    ],
    primaryMuscles: ['quadriceps', 'glutes'],
    secondaryMuscles: ['hamstrings', 'calves'],
  },
  {
    id: '00000000-0000-0000-0000-000000000020',
    name: 'Barbell Romanian Deadlift',
    category: 'legs',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/jEy_czb3RKA',
    thumbnailUrl: 'https://img.youtube.com/vi/jEy_czb3RKA/mqdefault.jpg',
    instructions: [
      'Stand with feet hip-width apart, holding the barbell at hip level with an overhand grip.',
      'Hinge at the hips and push your glutes back while keeping a slight bend in the knees.',
      'Lower the bar along your legs until you feel a deep stretch in your hamstrings.',
      'Drive your hips forward to return to the starting position, squeezing your glutes at the top.',
    ],
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['lower back', 'traps'],
  },
  {
    id: '00000000-0000-0000-0000-000000000021',
    name: 'Machine Leg Curl',
    category: 'legs',
    equipment: 'machine',
    videoUrl: 'https://www.youtube.com/embed/1Tq3QdYUuHs',
    thumbnailUrl: 'https://img.youtube.com/vi/1Tq3QdYUuHs/mqdefault.jpg',
    instructions: [
      'Lie face down on the leg curl machine with the pad just above your ankles.',
      'Grip the handles for stability and keep your hips pressed into the bench.',
      'Curl the weight up by flexing your knees, bringing your heels toward your glutes.',
      'Lower the weight slowly back to the starting position.',
    ],
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: ['calves'],
  },

  // ========== CORE (4) ==========
  {
    id: '00000000-0000-0000-0000-000000000022',
    name: 'Bodyweight Plank',
    category: 'core',
    equipment: 'bodyweight',
    videoUrl: 'https://www.youtube.com/embed/ASdvN_XEl_c',
    thumbnailUrl: 'https://img.youtube.com/vi/ASdvN_XEl_c/mqdefault.jpg',
    instructions: [
      'Start in a forearm plank position with elbows directly under your shoulders.',
      'Keep your body in a straight line from head to heels.',
      'Engage your core, glutes, and quads to maintain the position.',
      'Hold for the prescribed time without letting your hips sag or pike up.',
    ],
    primaryMuscles: ['rectus abdominis', 'transverse abdominis'],
    secondaryMuscles: ['obliques', 'lower back', 'shoulders'],
  },
  {
    id: '00000000-0000-0000-0000-000000000023',
    name: 'Cable Woodchop',
    category: 'core',
    equipment: 'cable',
    videoUrl: 'https://www.youtube.com/embed/pAplQXk3dkU',
    thumbnailUrl: 'https://img.youtube.com/vi/pAplQXk3dkU/mqdefault.jpg',
    instructions: [
      'Set the cable to the highest position and stand sideways to the machine.',
      'Grip the handle with both hands and arms extended.',
      'Rotate your torso diagonally downward across your body in a chopping motion.',
      'Return to the start under control and complete all reps before switching sides.',
    ],
    primaryMuscles: ['obliques'],
    secondaryMuscles: ['rectus abdominis', 'shoulders', 'hips'],
  },
  {
    id: '00000000-0000-0000-0000-000000000024',
    name: 'Machine Ab Crunch',
    category: 'core',
    equipment: 'machine',
    videoUrl: 'https://www.youtube.com/embed/3jJcBqmafcI',
    thumbnailUrl: 'https://img.youtube.com/vi/3jJcBqmafcI/mqdefault.jpg',
    instructions: [
      'Adjust the seat and select an appropriate weight on the machine.',
      'Place your feet under the pads and grip the handles above your shoulders.',
      'Crunch forward by contracting your abs, bringing your chest toward your knees.',
      'Slowly return to the starting position without letting the weight stack rest.',
    ],
    primaryMuscles: ['rectus abdominis'],
    secondaryMuscles: ['obliques'],
  },
  {
    id: '00000000-0000-0000-0000-000000000025',
    name: 'Bodyweight Hanging Leg Raise',
    category: 'core',
    equipment: 'bodyweight',
    videoUrl: 'https://www.youtube.com/embed/hdng3Nm1x_E',
    thumbnailUrl: 'https://img.youtube.com/vi/hdng3Nm1x_E/mqdefault.jpg',
    instructions: [
      'Hang from a pull-up bar with an overhand grip, arms fully extended.',
      'Keep your legs straight and raise them up in front of you.',
      'Lift until your legs are parallel to the floor or higher.',
      'Lower your legs slowly back down without swinging.',
    ],
    primaryMuscles: ['rectus abdominis', 'hip flexors'],
    secondaryMuscles: ['obliques', 'forearms'],
  },

  // ========== CARDIO (2) ==========
  {
    id: '00000000-0000-0000-0000-000000000026',
    name: 'Bodyweight Burpees',
    category: 'cardio',
    equipment: 'bodyweight',
    videoUrl: 'https://www.youtube.com/embed/dZgVxmf6jkA',
    thumbnailUrl: 'https://img.youtube.com/vi/dZgVxmf6jkA/mqdefault.jpg',
    instructions: [
      'Start standing, then squat down and place your hands on the floor.',
      'Jump your feet back into a plank position.',
      'Perform a push-up, then jump your feet back toward your hands.',
      'Explosively jump up with arms overhead and repeat immediately.',
    ],
    primaryMuscles: ['full body'],
    secondaryMuscles: ['chest', 'quadriceps', 'shoulders', 'core'],
  },
  {
    id: '00000000-0000-0000-0000-000000000027',
    name: 'Kettlebell Swing',
    category: 'cardio',
    equipment: 'kettlebell',
    videoUrl: 'https://www.youtube.com/embed/YSxHifyI6s8',
    thumbnailUrl: 'https://img.youtube.com/vi/YSxHifyI6s8/mqdefault.jpg',
    instructions: [
      'Stand with feet slightly wider than shoulder-width, kettlebell on the floor in front.',
      'Hinge at the hips, grip the kettlebell, and hike it back between your legs.',
      'Drive your hips forward explosively to swing the kettlebell to chest height.',
      'Let the kettlebell swing back between your legs and repeat in a fluid motion.',
    ],
    primaryMuscles: ['glutes', 'hamstrings'],
    secondaryMuscles: ['core', 'shoulders', 'lower back'],
  },

  // ========== FULL-BODY (3) ==========
  {
    id: '00000000-0000-0000-0000-000000000028',
    name: 'Barbell Deadlift',
    category: 'full-body',
    equipment: 'barbell',
    videoUrl: 'https://www.youtube.com/embed/op9kVnSso6Q',
    thumbnailUrl: 'https://img.youtube.com/vi/op9kVnSso6Q/mqdefault.jpg',
    instructions: [
      'Stand with feet hip-width apart, the bar over your mid-foot.',
      'Hinge at the hips, bend your knees, and grip the bar just outside your legs.',
      'Brace your core, flatten your back, and drive through the floor to stand up.',
      'Lock out at the top with hips and knees fully extended, then lower under control.',
    ],
    primaryMuscles: ['hamstrings', 'glutes', 'lower back'],
    secondaryMuscles: ['quadriceps', 'traps', 'forearms', 'core'],
  },
  {
    id: '00000000-0000-0000-0000-000000000029',
    name: 'Dumbbell Thruster',
    category: 'full-body',
    equipment: 'dumbbell',
    videoUrl: 'https://www.youtube.com/embed/M0EQ-Z-gHgA',
    thumbnailUrl: 'https://img.youtube.com/vi/M0EQ-Z-gHgA/mqdefault.jpg',
    instructions: [
      'Hold a dumbbell in each hand at shoulder height with palms facing inward.',
      'Perform a full squat, keeping your chest up and core braced.',
      'Drive up explosively from the squat and press the dumbbells overhead in one fluid motion.',
      'Lower the dumbbells back to shoulder height as you descend into the next squat.',
    ],
    primaryMuscles: ['quadriceps', 'glutes', 'shoulders'],
    secondaryMuscles: ['triceps', 'core', 'hamstrings'],
  },
  {
    id: '00000000-0000-0000-0000-000000000030',
    name: 'Bodyweight Mountain Climbers',
    category: 'full-body',
    equipment: 'bodyweight',
    videoUrl: 'https://www.youtube.com/embed/nmwgirgXLYM',
    thumbnailUrl: 'https://img.youtube.com/vi/nmwgirgXLYM/mqdefault.jpg',
    instructions: [
      'Start in a high plank position with hands directly under your shoulders.',
      'Drive one knee toward your chest while keeping the other leg extended.',
      'Quickly switch legs in a running motion while maintaining plank form.',
      'Keep your hips level and core tight throughout the movement.',
    ],
    primaryMuscles: ['core', 'hip flexors'],
    secondaryMuscles: ['shoulders', 'quadriceps', 'chest'],
  },
]
